# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci(n)
  if n == 1
    return 1
  elsif n == 2
    return 2
  else
    fibonacci(n-1) + fibonacci(n-2)
  end
end

i = 1
sum = 0
fib = fibonacci(i)

while fib < 4_000_000
  if fib.even?
    sum += fib
  end
  i += 1
  fib = fibonacci(i)
end
puts sum
